#!/usr/bin/perl


use strict;
use warnings;

use File::Find;
use File::Copy;

my $hook_dir = "/home/twist/bin/githooks";
my @found_hooks;
my @hooks = ("pre-commit", "post-commit");

main();


sub main
{

	my $init = 0;
	my $repo_only = 0;

	for(my $i = 0; $i < @ARGV; $i++)
	{
		if ($ARGV[$i] =~ "--init")
		{
			$init = 1;
		}
		if ($ARGV[$i] =~ "--repositorie-only")
		{
			$repo_only = 1;
		}
	}






	if ($init == 1)
	{
		init_repository($repo_only);
	}
		

}





sub init_repository
{
	print "INIT";
        get_all_hooks();
        foreach my $hook (@found_hooks)
        {
                copy($hook, ".git/hooks/");
        }
        foreach my $hook (@hooks)
        {
                chmod(0744, ".git/hooks/$hook");
        }

}


sub get_all_hooks
{
     print   find(\&wanted, $hook_dir);        

}


sub wanted
{
        /\.git/ and $File::Find::prune = 1;
        foreach my $hook (@hooks)
        {
                if ($_ =~ /$hook/)
                {
                        push(@found_hooks, $File::Find::name);
                }
        }


}
