#!/usr/bin/perl


use strict;
use warnings;

use File::Find;
use File::Copy;

my $hook_dir = "/home/twist/projects/githooks";
my @found_hooks;
my @hooks = ("pre-commit", "post-commit");

main();


sub main
{

	my $init = 0;
	my $repo_only = 0;

	for(my $i = 0; $i < @ARGV; $i++)
	{
		if ($ARGV[$i] =~ "--init")
		{
			$init = 1;
		}
		if ($ARGV[$i] =~ "--repositorie-only")
		{
			$repo_only = 1;
		}
	}






	if ($init == 1)
	{
		hook_menu();
		init_repository($repo_only);
	}
		

}




sub hook_menu
{

        get_all_hooks();
	print "i found the following hooks:\n----------------------------\n";
	my $i = 1;
	my @hooks = @found_hooks;
	my @hooks_with_info;
	foreach my $hook (@hooks)
	{
		my $hook_data = parse_hook($hook);
		push(@hooks_with_info,$hook_data) ;

	}

}

sub parse_hook
{
	my ($hook) = @_;
	
	open FILE, ($hook) or die "ADASSD";
	my $hook_data = {};

	#defaults
	$hook_data->{"HMU_NAME"} = $hook;
	$hook_data->{"HMU_DESCR"} = "no description given";

	while ( my $line = <FILE>)
	{
		if ($line =~ /HMU_NAME: (.*)$/)
		{
			$hook_data->{"HMU_NAME"} = $1;
		}
		if ($line =~ /HMU_DESCR: (.*)$/)
		{
			$hook_data->{"HMU_DESCR"} = $1;
		}
	}
	close FILE;
	return $hook_data;
}

sub init_repository
{
        foreach my $hook (@found_hooks)
        {
                copy($hook, ".git/hooks/");
        }
        foreach my $hook (@hooks)
        {
                chmod(0744, ".git/hooks/$hook");
        }

}


sub get_all_hooks
{
     find(\&wanted, $hook_dir);  

}


sub wanted
{
        /\.git/ and $File::Find::prune = 1;
        foreach my $hook (@hooks)
        {
                if ($_ =~ /$hook/)
                {
                        push(@found_hooks, $File::Find::name);
                }
        }


}
